### ISSUE TITLE
Syslog/Systemd log format support or example

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seqcli#34]
It should be possible to ingest logs from systemd's `journalctl` or `/var/log/syslog` easily with the `seqcli ingest` command.

**Comment by sereeth** [comment]
Tried it out, get this when running the config command to set serverUrl

```
Could not update config: Exception has been thrown by the target of an invocation.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.PlatformNotSupportedException: Windows Data Protection API (DPAPI) is not supported on this platform.
   at System.Security.Cryptography.ProtectedData.Protect(Byte[] userData, Byte[] optionalEntropy, DataProtectionScope scope)
   at SeqCli.Util.MachineScopeDataProtection.Protect(String value) in C:\projects\seqcli\src\SeqCli\Util\MachineScopeDataProtection.cs:line 53
   at SeqCli.Config.SeqCliConnectionConfig.set_ApiKey(String value) in C:\projects\seqcli\src\SeqCli\Config\SeqCliConnectionConfig.cs:line 50
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at SeqCli.Cli.Commands.ConfigCommand.Set(SeqCliConfig config, String key, String value) in C:\projects\seqcli\src\SeqCli\Cli\Commands\ConfigCommand.cs:line 114
   at SeqCli.Cli.Commands.ConfigCommand.Run() in C:\projects\seqcli\src\SeqCli\Cli\Commands\ConfigCommand.cs:line 54
```

**Comment by nblumhardt** [comment]
Thanks for letting us know, @sereeth 👍 .. looks like a cross-platform bug, we'll dig into this shortly.

In the meantime, you can pass `--apikey=....` on the command-line to each command, instead of storing it in the config file, to work around this.

Thanks again!

**Comment by sereeth** [comment]
What about passing the serverUrl?   What I did was hand bake the SeqConfig.json but unsure where it should be and if the format is right...


{
        "connection": {
                "apiKey": "sdfsdsff",
                "serverUrl": "http://sdfsdfsfd:5341"
        }
}

**Comment by nblumhardt** [comment]
Hi @sereeth - passing `--server=...` will work for the server part.

The hand-baked configuration might work as you've shown - it's hard to say whether the bug mentioned above will still kick in anywhere, though. Hoping we'll have a proper fix out soon.
