### ISSUE TITLE
Exception trying to perform any query

### ISSUE THREAD

**Issue by BrianL-STCU** [datalust/seqcli#60]
After following the [Getting Started instruction](https://github.com/datalust/seqcli/blob/dev/README.md#getting-started), SeqCli was giving me an error (likely because we require authentication):

```text
The command failed: 401 - Please log in.
Seq.Api.Client.SeqApiException: 401 - Please log in.
   at Seq.Api.Client.SeqApiClient.<HttpSendAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Seq.Api.Client.SeqApiClient.<PostReadStringAsync>d__17`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Seq.Api.ResourceGroups.ApiResourceGroup.<GroupPostReadStringAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Seq.Api.ResourceGroups.DataResourceGroup.<QueryCsvAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SeqCli.Cli.Commands.QueryCommand.<Run>d__8.MoveNext() in C:\projects\seqcli\src\SeqCli\Cli\Commands\QueryCommand.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SeqCli.Cli.Command.<Run>d__11.MoveNext() in C:\projects\seqcli\src\SeqCli\Cli\Command.cs:line 83
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SeqCli.Cli.Command.<Invoke>d__10.MoveNext() in C:\projects\seqcli\src\SeqCli\Cli\Command.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SeqCli.Cli.CommandLineHost.<Run>d__2.MoveNext() in C:\projects\seqcli\src\SeqCli\Cli\CommandLineHost.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SeqCli.Program.<Main>d__0.MoveNext() in C:\projects\seqcli\src\SeqCli\Program.cs:line 51
```

After creating an API key token and manually putting it in `$home\SeqCli.json`, I get:

```text
The command failed: 500 - An unhandled error occurred while serving the request (token: ████████████████████████████████).
Seq.Api.Client.SeqApiException: 500 - An unhandled error occurred while serving the request (token: ████████████████████████████████).
   at Seq.Api.Client.SeqApiClient.<HttpSendAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Seq.Api.Client.SeqApiClient.<PostReadStringAsync>d__17`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Seq.Api.ResourceGroups.ApiResourceGroup.<GroupPostReadStringAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Seq.Api.ResourceGroups.DataResourceGroup.<QueryCsvAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SeqCli.Cli.Commands.QueryCommand.<Run>d__8.MoveNext() in C:\projects\seqcli\src\SeqCli\Cli\Commands\QueryCommand.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SeqCli.Cli.Command.<Run>d__11.MoveNext() in C:\projects\seqcli\src\SeqCli\Cli\Command.cs:line 83
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SeqCli.Cli.Command.<Invoke>d__10.MoveNext() in C:\projects\seqcli\src\SeqCli\Cli\Command.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SeqCli.Cli.CommandLineHost.<Run>d__2.MoveNext() in C:\projects\seqcli\src\SeqCli\Cli\CommandLineHost.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SeqCli.Program.<Main>d__0.MoveNext() in C:\projects\seqcli\src\SeqCli\Program.cs:line 51
```

On the Seq server, **Settings** → **Diagnostics** → **Download a full diagnostic report** contains:

```text
Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.Boolean'. Path 'IsRestricted', line 1, position 113. ---> System.InvalidCastException: Null object cannot be converted to a value type.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Seq.Server.Web.SeqNancyModule.ReadBody[T]()
   at Seq.Server.Web.Api.SignalContentModule.ReadPostedSignal()
   at Seq.Server.Web.Api.EventsModule.<.ctor>b__5_1(Object p)
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
```

**Comment by nblumhardt** [comment]
Ah, thank you for the report, Brian.

I believe this is a regression due to us updating `seqcli` to use version 5 of _Seq.Api.dll_ - I think I can spot [the issue over there](https://github.com/datalust/seq-api/blob/dev/src/Seq.Api/Model/Signals/SignalEntity.cs#L27), I'll try modifying the new version of the assembly so that the old `IsRestricted` value isn't sent except when non-default.
