### ISSUE TITLE
Exception when trying to apply filter on ingest

### ISSUE THREAD

**Issue by kevbry** [datalust/seqcli#87]
When attempting to apply any filter using ingest, a MissingMethodException is thrown. The filter I'd like to use would be based on date, but the level filter from the seqcli docs also does not seem to work.

Initial installation was 5.0.2375. Updated to 5.0.2394, which also fails the same way.

```
PS C:\Temp> seqcli ingest -i .\unified.log --json --filter="@Level <> 'Debug'" -p Environment=Test
Ingestion failed: Method not found: 'Superpower.Model.Token`1<!0> Superpower.Tokenizer`1.get_Previous()'.
System.MissingMethodException: Method not found: 'Superpower.Model.Token`1<!0> Superpower.Tokenizer`1.get_Previous()'.
   at Serilog.Filters.Expressions.Parsing.FilterExpressionTokenizer.Tokenize(TextSpan stringSpan)+MoveNext()
   at Superpower.Tokenizer`1.TryTokenize(String source)
   at Serilog.Filters.Expressions.Parsing.FilterExpressionParser.TryParse(String filterExpression, FilterExpression& root, String& error)
   at Serilog.Filters.Expressions.FilterLanguage.TryCreateFilter(String expression, Func`2& filter, String& error)
   at Serilog.Filters.Expressions.FilterLanguage.CreateFilter(String expression)
   at SeqCli.Cli.Commands.IngestCommand.Run() in C:\projects\seqcli\src\SeqCli\Cli\Commands\IngestCommand.cs:line 79
PS C:\Temp> seqcli version
5.0.165
PS C:\Temp> seq version
5.0.2394
```

**Comment by kevbry** [comment]
From a quick look around it looks as though seqcli is referencing serilog.filters.expressions 1.1.0 and superpower 2.0. Looks like serilog.filters.expressions 2.0 is where compatibility with superpower 2.0 was added. 
Updating Serilog.Filters.Expressions.dll to version 2.0 from here:

https://www.nuget.org/packages/Serilog.Filters.Expressions/2.0.0

seems to fix the issue.

**Comment by nblumhardt** [comment]
Thanks for the report and investigation, @kevbry - we'll sort this out :+1:

**Comment by kevbry** [comment]
Thanks for the fix, and the fantastic software

**Comment by nblumhardt** [comment]
Thanks!
